remote_theme: community-resource-network/theme
title: Community Resource Network
description: Bringing food to the communities of Puget Sound

lang: en-US

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed

teams:
  - name: Red-Bell
    stores: _teams/red-bell/stores.yml
  - name: South Snohomish
    stores: _teams/south-snohomish/stores.yml
  - name: Kirkland
    stores: _teams/kirkland/stores.yml
  - name: Kent-Federal Way
    stores: _teams/kent-federal-way/stores.yml

navbar:
  - title: Volunteer
    permalink: /volunteer
  - title: Partners
    permalink: /partners
  - title: Contact
    permalink: /contact
  - title: About
    permalink: /about
