remote_theme: community-resource-network/theme
title: Community Resource Network
description: Bringing food to the communities of Puget Sound

lang: en-US

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed

navbar:
  - title: Volunteer
    permalink: /volunteer
  - title: Partners
    permalink: /partners
  - title: Contact
    permalink: /contact
  - title: About
    permalink: /about
